config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :departments
  resources :staffs
  resources :admins
  root 'departments#index'
  

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get    '/signup',  to: 'admins#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
	has_many :staffs, dependent: :destroy
end

app/models/staff.rb
class Staff < ApplicationRecord
	# searchkick
	# Staff.reindex
	belongs_to :department
	default_scope -> { order(created_at: :desc) }
	before_save { self.email = email.downcase }

	# VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	# validates :email, presence: true, length: { maximum: 255 },
	#                     format: { with: VALID_EMAIL_REGEX }            
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
      @departments = Department.all
  end

  
  # GET /departments/1
  # GET /departments/1.json
  def show
    
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
	def show
  
end

def index
    # if params[:query].present?
    #       @staffs = Staff.search params[:query], page: params[:page], per_page: 30
    # else
      @staffs = Staff.all.paginate(page: params[:page])
    # end
  end

def create
    
  end

def edit
    @staff = Staff.find(params[:id])
  end

def update
    
  end

  def new
    @staff = Staff.new
  end

  def find id
    staff = Staff.find_by(id: id)
  end

  def destroy
    @staff = Staff.find(params[:id])
    @department = Department.find_by(id: @staff.department_id)
    @staff.destroy
    flash[:success] = "Staff deleted"
    redirect_to @department
  end

private
    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:id, :name,:phone, :address, :email, :out, :position, :status, :gender, :department_id)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(admin)
    	session[:admin_id] = admin.id
  end

  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id])
  end

  def logged_in?
    !current_admin.nil?
  end

  def log_out
    session.delete(:admin_id)
    @current_admin = nil
  end
end

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<div class="wrapper row2">
  <main id="container" class="clear"> 
    <!-- container body --> 
    <!-- ########################################################################################## -->
    <div id="" class="clear">
      <%= will_paginate @staffs, :style => 'margin-left: 36%' %>
        <table data-id="<%= @department.name %>" class="table" id="acrylic">
  <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Position</th>
        <th>Status</th>
      </tr>
    </thead>

    <% if @department.staffs.any? %>
      
      <tbody>
       <%= render @staffs %>
      </tbody>
      
    <% end %>
</table>
<%= will_paginate @staffs, :style => 'margin-left: 36%' %>
    </div>
  </main>
</div>







<div style="display: none;" id="orderModal" class="modal" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close" data-dismiss="modal" aria-hidden="true">&times;</span>
      <h2>Staff Detail</h2>
    </div>
    <div class="modal-body" id="orderDetails">
         
    </div>
    <div class="modal-footer">
      
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>
</div>

<script>
  $(function() { 
  $('#orderModal').modal({
        keyboard: true,
        show:false,
    });

  
  var longpress = 500;
  
  var start;

  $(".table").find('tr[data-id]').on( 'mousedown', function( e ) {
      start = new Date().getTime();
  } );
    
  $(".table").find('tr[data-id]').on( 'mouseleave', function( e ) {
        start = 0;
    } );
    
  $(".table").find('tr[data-id]').on( 'mouseup', function( e ) {
      if ( new Date().getTime() >= ( start + longpress )  ) {
          $('#orderModal').attr('style', 'display: none !important');
  
    var kid_id = $(this).data('id');
    $.getJSON("/staffs/" + kid_id, function(data) {
        var tr_id = "tr[data-id = "+ data.id +"]";
    window.location.href = "<%= request.base_url %>" + $(".table").find(tr_id).data("link");
    
  
  });

      } else {
     
    $('#orderDetails').attr('style', '');
    
    var kid_id = $(this).data('id');
    $.getJSON("/staffs/" + kid_id, function(data) {

    $('.modal-backdrop').remove();
      $('#orderDetails').html('<%= j render 'modal'%>');
    var dp = $(".table").data('id');
    $('#name').html($('<span>'+ data.name + '</span>'));
    $('#depart').html($('<span>'+ dp + '</span>'));
    $('#email').html($('<a href="mailto:'+data.email+ '">'+data.email+'</a>'));
    $('#address').html($('<span>'+ data.address + '</span>'));
    $('#phone').html($('<span>'+ data.phone + '</span>'));
    $('#gender').html($('<span>'+ data.gender + '</span>'));
    $('#created-at').html($('<span>'+ data.created_at + '</span>'));
    $('#modal').modal('show');
  });

      }
  } );

});
</script>

app/views/layouts/_footer.html.erb
<footer style="clear: both;">
		<div class="container" id="footer-head">
			<div class="rows">
				<div class="col-md-4">
					
					<ul>
						<li><h2>Our Company</h1></li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
					</ul>
				</div>
				<div class="col-md-4">
					
					<ul>
						<li><h2>Our Service</h2></li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
						<li>About us</li>
					</ul>
				</div>	
				<div class="col-md-4">
					<ul>
						<li><h2>Our Contact</h2></li>
						<li>5252 E Walnut Ave, Orange, California, United States.</li>
						<li>hello@construction.me +62 (0) 274 441 5005</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="copy rows">
			<div class="container">
				<div class="copy-left col-md-6">
				<p>COPYRIGHT &copy 2016 <span style="font-weight: bold; color: #e67e22">TEMPLATENINJA</span>. ALL RIGHT RESERVED.</p>
				</div>
				<div class="copy-right col-md-6">
					<ul style="padding-left: 300px;">
						<li><i class="fa fa-facebook-square" aria-hidden="true"></i></li>
						<li><i class="fa fa-twitter" aria-hidden="true"></i></li>
						<li><i class="fa fa-youtube" aria-hidden="true"></i></li>
						<li><i class="fa fa-instagram" aria-hidden="true"></i></li>
					</ul>
				</div>
			</div>
		</div>
</footer>

app/views/layouts/_header.html.erb
<script>
  $(document).ready(function(){
    //Handles menu drop down
    // $('.dropdown-menu').find('form').click(function (e) {
    //     e.stopPropagation();
    // });

    $('.dropdown-toggle').dropdown();
});
</script>
<div class="wrapper row1"> 
  <!-- ################################################################################################ -->
  <header id="header" class="clear"> 
    <!-- ################################################################################################ -->
    <div id="logo">
      <h1><%= link_to "Home Page", root_path %></h1>
      <p>Company Sell Onion</p>
    </div>
    <nav>
      <ul class="clear">
        <li class="active"><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
                     <a href="http://www.jquery2dotnet.com" class="dropdown-toggle" data-toggle="dropdown">Add Staff <b class="caret"></b></a>
                     <ul class="dropdown-menu" style="padding: 15px;min-width: 250px;">
                        <li>
                           <%= render 'staffs/form' %>
                        </li>
                     </ul>
        </li>
        <li><a class="drop" href="#">Account</a>
          <ul>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <%end%>
      </ul>
    </nav>
    <!-- ################################################################################################ --> 
  </header>
  <!-- ################################################################################################ -->
  <div id="slider" class="jcarousel-wrapper">
    <div id="slider_content" class="jcarousel">
      <ul>
        <li>
          <figure><a href="#"><img src="/assets/1.png" alt="" ></a>
            <figcaption>
              <h2>Cursus penati saccum nulla.</h2>
              <p>Nullamlacus dui ipsum conseque loborttis non euisque morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque congue magnis vestibulum quismodo nulla et feugiat adipiscinia pellentum leo&hellip;</p>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure><a href="#"><img src="/assets/2.png" alt=""></a>
            <figcaption>
              <h2>Cursus penati saccum nulla.</h2>
              <p>Nullamlacus dui ipsum conseque loborttis non euisque morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque congue magnis vestibulum quismodo nulla et feugiat adipiscinia pellentum leo&hellip;</p>
            </figcaption>
          </figure>
        </li>
        <li>
          <figure><a href="#"><img src="/assets/3.png" alt=""></a>
            <figcaption>
              <h2>Cursus penati saccum nulla.</h2>
              <p>Nullamlacus dui ipsum conseque loborttis non euisque morbi penas dapibulum orna. Urnaultrices quis curabitur phasellentesque congue magnis vestibulum quismodo nulla et feugiat adipiscinia pellentum leo&hellip;</p>
            </figcaption>
          </figure>
        </li>
      </ul>
    </div>
    <!-- Previous Next --> 
    <a href="#" id="featured-item-prev" class="jcarousel-control-prev">&laquo; Previous</a> <a href="#" id="featured-item-next" class="jcarousel-control-next">Next &raquo;</a> 
    <!-- / Previous Next --> 
  </div>
  <!-- ########################################################################################## --> 
</div>

        
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery.min.js' %>
    <%= javascript_include_tag 'jquery.grayscale.js' %>
    <%= javascript_include_tag 'jquery.jcarousel.pack.js' %>
    <%= javascript_include_tag 'jquery.jcarousel.setup.js' %>


    <%= render 'layouts/shim' %>
    
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> -->
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    
    	<% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      	<%= yield %>
    
    
    <div style="clear: both;">
      <%= render 'layouts/footer' %>
  </div>
  </body>
  
</html>

app/views/staffs/edit.html.erb
<% if logged_in? %>
<h1 style="color: wheat">Update profile</h1>

<div class="row edit">
  <div class="col-md-6 col-md-offset-3">
    <h2 style="color: gold"><%= @staff.name %></h2>
    <%= form_for(@staff) do |f| %>
  	 <%= render 'shared/error', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :position %>
      <%= f.text_field :position, class: 'form-control' %>
      
      <%= f.label :status %>
      <%= f.text_field :status, class: 'form-control' %>

      <%= f.label :gender %>
      <%= f.text_field :gender, class: 'form-control' %>

      <!-- <%= select("@staff", "department_id", Department.all.collect {|d| [ d.name, d.id ] }, { include_blank: false }) %> -->
      <%= f.select :department_id, Department.all.collect { |p| [ p.name, p.id ] }, include_blank: false %>

      <%= f.label :out , "Not Out"%>
      <%= f.radio_button :out, "0" %>
      
      <%= f.label :out , 'Out' %>
      <%= f.radio_button :out, "1" %>
      
      <br>
      <%= f.submit "SAVE CHANGE", class: "btn btn-primary" %>
      <%= link_to "DELETE", @staff, method: :delete,data: { confirm: "You sure?" }, class: "btn btn-danger", style: "margin-left: 10px;width: 130px" %>
    <% end %>

    <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"/>
    
  </div>
</div>
<% else %>
    <%= flash.now[:danger] = "Use Must Login As Admin To Edit The Staff" %>
    <button style="margin-left: 20%" class="btn btn-warning" id="back"> Back? </button>
    <button class="btn btn-warning" id="login"> Login? </button>
<% end %>
<script>
   $(function(){
      $('#back').on('click', function(){
          window.history.back();
      });
      $('#login').on('click', function(){
          window.location.href = "<%= request.base_url %>" + "/login";
      });
   });
</script>

app/views/staffs/index.html.erb
<table class="table" id="acrylic">
	<thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Position</th>
        <th>Status</th>
      </tr>
    </thead>  
      <tbody>
       <%= render @staffs %>
      </tbody>
</table>
<%= will_paginate @staffs, :style => "margin-left: 30%" %>
<div style="display: none;" id="orderModal" class="modal" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-content">
    <div class="modal-header">
      <span class="close" data-dismiss="modal" aria-hidden="true">&times;</span>
      <h2>Staff Detail</h2>
    </div>
    <div class="modal-body" id="orderDetails">
         
    </div>
    <div class="modal-footer">
      
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
  </div>

</div>
<script>


$(function() { 
  $('#orderModal').modal({
        keyboard: true,
        show:false,
    });

  // how many milliseconds is a long press?
  var longpress = 500;
  // holds the start time
  var start;

  $(".table").find('tr[data-id]').on( 'mousedown', function( e ) {
      start = new Date().getTime();
  } );
    
  $(".table").find('tr[data-id]').on( 'mouseleave', function( e ) {
        start = 0;
    } );
    
  $(".table").find('tr[data-id]').on( 'mouseup', function( e ) {
      if ( new Date().getTime() >= ( start + longpress )  ) {
          $('#orderModal').attr('style', 'display: none !important');
          // $(".table").find('tr[data-id]').on('click', function () {
    var kid_id = $(this).data('id');
    $.getJSON("/staffs/" + kid_id, function(data) {
        var tr_id = "tr[data-id = "+ data.id +"]";
    window.location.href = "<%= request.base_url %>" + $(".table").find(tr_id).data("link");
    
    // $('.modal-backdrop').remove();
  });
// })
      } else {
     
    $('#orderDetails').attr('style', '');
    
    var kid_id = $(this).data('id');
    $.getJSON("/staffs/" + kid_id, function(data) {
      $('#orderDetails').html('<%= j render 'departments/modal'%>');
    var dp = $(".table").data('id');
    $('#name').html($('<span>'+ data.name + '</span>'));
    $('#depart').html($('<span>'+ dp + '</span>'));
    $('#email').html($('<a href="mailto:'+data.email+ '">'+data.email+'</a>'));
    $('#address').html($('<span>'+ data.address + '</span>'));
    $('#phone').html($('<span>'+ data.phone + '</span>'));
    $('#gender').html($('<span>'+ data.gender + '</span>'));
    $('#created-at').html($('<span>'+ data.created_at + '</span>'));
    $('#modal').modal('show');
    $('.modal-backdrop').remove();
  });

      }
  } );

});
   
</script>

app/views/static_pages/home.html.erb
<p> hello </p>